### ISSUE TITLE
Conda installable

### ISSUE THREAD

**Issue by brwnj** [lgautier/fastq-and-furious#1]
Would be nice to have the compiled version available for install through [bioconda](https://github.com/bioconda/bioconda-recipes).

**Comment by lgautier** [comment]
May be more a feature request for bioconda's issue tracker ?

**Comment by brwnj** [comment]
That's an option, but it's always nice to have the developers maintain their own recipe. Then in your docs here, installation instructions include `conda install -c bioconda fastqandfurious`. Developer support isn't required and seldom is actually performed by the developer. This was just a request. Thanks for your work.

**Comment by lgautier** [comment]
> That's an option, but it's always nice to have the developers maintain their own recipe.

I am not using conda / bioconda much myself, unfortunately.

**Comment by lgautier** [comment]
I won't be able to do much about, so I moved the issue to bioconda.
