### ISSUE TITLE
Add `Bio.SeqIO.QualityIO.FastqGeneralIterator` to  benchmark

### ISSUE THREAD

**Issue by lgautier** [lgautier/fastq-and-furious#2]
@peterjc's request - see https://twitter.com/pjacock/status/829353750678618112

**Comment by lgautier** [comment]
Added to the benchmark, and the README and throughput.png were updated to also add it. Only `fastqandfurious_c` still faster... for now.

Note: I am the only one to learn about `Bio.SeqIO.QualityIO.FastqGeneralIterator` at this occasion ?

**Comment by peterjc** [comment]
Thanks. Clearly this is still too hidden in the current Biopython documentation.

An old but relevant blog post: https://news.open-bio.org/2009/09/25/biopython-fast-fastq/

**Comment by peterjc** [comment]
I think the README could be a little clearer in the comparisons that you don't care about the quality strings at all.

``Bio.SeqIO.QualityIO.FastqGeneralIterator(handle)`` just gives three strings per record (title, sequence, quality ASCII string).

``Bio.SeqIO.parse(handle, "fastq")`` calls this low-level parser, decodes the quality ASCII string into integer scores, and creates the ``Seq`` and ``SeqRecord`` objects.

Your ``biopython_adapter`` skips decoding the quality strings (which is perfectly sensible in your use case).

**Comment by lgautier** [comment]
> I think the README could be a little clearer in the comparisons that you don't care about the quality strings at all.

Not quite. The benchmark returns entry header/title/name/ID, sequence, and quality. Just as `Bio.SeqIO.QualityIO.FastqGeneralIterator` does.

When using a `bytes` object there little to "decode" as each byte in a sequence *is* the quality score offset by 33. 

> Your biopython_adapter skips decoding the quality strings (which is perfectly sensible in your use case).

In the specific case of the adapter, yes. Your comment prompted me to check whether you had the quality and found it buried under the attribute `letter_annotations` (a `dict`) and a list of integer associated with the key name 'phred_quality'.

Adding to the `biopython_adapter` (creating the very exact same) is leads to perf going from ~30MB/s down to about 14MB/s. I allowed myself to tweak this just a little though: since the quality does not a mutable sequence (a `list`) and items in the sequence are all simple (short) integers, using a more efficient representation (a Python `array.array`) and pushing the "-33"m offset to C bring the performances back to 25.5MB/s. All this is in revision 3dc5e1d6ac0857bdae16b60ccbd9f715f0ff6314.

**Comment by lgautier** [comment]
> Thanks. Clearly this is still too hidden in the current Biopython documentation.

I wonder how many people end up reimplementing a FASTQ parser because they think that `Bio.SeqIO` is too slow...

**Comment by peterjc** [comment]
Thanks for those details - perhaps we should switch the Biopython SeqIO parser to use ``array.array`` rather than a ``list`` of integers?

**Comment by peterjc** [comment]
Biopython Tutorial updated to make low-level parsers more prominent,

SeqIO chapter: https://github.com/biopython/biopython/blob/68a204b4b479c9df4bb55401028b9e6c9a90d14d/Doc/Tutorial/chapter_seqio.tex#L1242

Cookbook chapter:
https://github.com/biopython/biopython/blob/68a204b4b479c9df4bb55401028b9e6c9a90d14d/Doc/Tutorial/chapter_cookbook.tex#L58

**Comment by lgautier** [comment]
> Biopython Tutorial updated to make low-level parsers more prominent,

May be put a not about it in the docstrings in `SeqIO` as well ? Old-timers are more likely to check the docstring than read a tutorial / manual, I'd think.

**Comment by lgautier** [comment]
> Thanks for those details - perhaps we should switch the Biopython SeqIO parser to use array.array rather than a list of integers?

Your call(*), you'd need to pair with a C-level function to observe similar speed gains to the one in `fastqandfutrious` (function `fastqandfurious._fastqandfurious.byteoffset` - check the example at the end of the README).

(*: The philosophy in `fastqandfurious` is a bit different in the sense that the parser is doing as little as possible and what to extract from the FASTQ is left to a user through the callback `entryfunc`. For example if only the beginning of the sequence if of interest to split trim barcodes, `fastqandfurious` can be even faster than in the current benchmark).

**Comment by peterjc** [comment]
External eyes on the documentation is great for a new perspective, thanks! Added this to the ``Bio.SeqIO`` main docstring: https://github.com/biopython/biopython/commit/10aba348711fb06dac098abd1e09e76f7bec38dd

GSoC 2014 student Evan Parker explored lazy-loading in ``Bio.SeqIO``, a lot is possible but the changes to the parsing code were quite invasive. Perhaps a less ambitious approach would have been more practical? http://biopython.org/wiki/Google_Summer_of_Code http://blog.evanaparker.com

In terms of the public API, switching from a list to an array has minimal impact. The trick would be getting a good speedup in building an array versus the current code building a list... let's continue any discussion on https://github.com/biopython/biopython/pull/1057

Thank you!

**Comment by lgautier** [comment]
Commenting what is specific to `fastqandfurious` here: the idea here is slightly different from lazy loading in the sense that a chunk of data **is** loaded when read from disk, or any kind of stream.
