### ISSUE TITLE
Paired-end read workflow?

### ISSUE THREAD

**Issue by caleblareau** [lgautier/fastq-and-furious#3]
Hi @lgautier -- this looks great; I think that it could substantially speed up my analyses. 

I've implemented a non-trivial example for single-end read (following the documentation), but I was curious what your recommended approach would be for a pair-end sample. In essence, I want to be able to perform an operation to each of the ends as I iterate read-by-read through two files. 

I'm presently considering using something similar to the following:

```
gen = function_that_returns_a_generator(param1, param2)
if gen: # in case the generator is null
    while True:
        try:
            print gen.next()
        except StopIteration:
            break
``` 

from here: https://stackoverflow.com/questions/11539194/how-to-loop-through-a-generator

Thanks!

**Comment by lgautier** [comment]
To consume data from several iterators in parallel, here one for each end in the pair, use [`zip()`](https://docs.python.org/3/library/functions.html#zip).

Not an issue with the package. Closing.
