### ISSUE TITLE
TypeError: biopython_entryfunc() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by evanbiederstedt** [lgautier/fastq-and-furious#7]
Hi there

This may be another README confusion, but I've yet to figure out what is the problem---I'm trying the code in the README for the biopython adapter code:

```
from fastqandfurious import fastqandfurious
from fastqandfurious.fastqandfurious import entryfunc
from fastqandfurious._fastqandfurious import arrayadd_b
from Bio.SeqRecord import SeqRecord
from array import array

def biopython_entryfunc(buf, posarray):
    name = buf[posarray[0]:posarray[1]].decode('ascii')
    quality = array('b')
    quality.frombytes(buf[posarray[4]:posarray[5]])
    arrayadd_b(quality, -33)
    entry = SeqRecord(seq=buf[posarray[2]:posarray[3]].decode('ascii'),
                      id=name,
                      name=name,
                      letter_annotations={'phred_quality': quality})
    return entry

bufsize = 20000
with open("a/fastq/file.fq") as fh:
    it = fastqandfurious.readfastq_iter(fh, bufsize, biopython_entryfunc)
    for entry in it:
        # do something
	pass
```

I run into the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/evanbiederstedt/.pyenv/versions/3.6.8/lib/python3.6/site-packages/fastqandfurious/fastqandfurious.py", line 223, in readfastq_iter
    yield entryfunc(blob, posbuffer, globaloffset)
TypeError: biopython_entryfunc() takes 2 positional arguments but 3 were given
```

**Comment by evanbiederstedt** [comment]
For what it's worth, the only reason I became interested in using the `biopython_entryfunc` is this seems like the intelligent way to at a later point write the FASTQ to file via `SeqIO`. (If there's an obvious way to write FASTQs via the binary tuples output by fastq-and-furious, perhaps that's a better approach...I haven't investigated the performance implications.)

**Comment by lgautier** [comment]
Here again this is incorrect or outdated information in the README.

The code in the benchmark script should contain the correct code:
https://github.com/lgautier/fastq-and-furious/blob/master/src/demo/benchmark.py#L135

**Comment by evanbiederstedt** [comment]
Apologies---I somehow missed that.

Yes, this certainly works. 

```

def biopython_entryfunc(buf, posarray, globaloffset):
    name = buf[posarray[0]:posarray[1]].decode('ascii')
    quality = array('b')
    quality.frombytes(buf[posarray[4]:posarray[5]])
    arrayadd_b(quality, -33)
    entry = SeqRecord(seq=buf[posarray[2]:posarray[3]].decode('ascii'),
                      id=name,
                      name=name,
                      letter_annotations={'phred_quality': quality})
    return entry
```

The sole reason I was trying this is I began to write a FASTQ to file, and thought maybe using the Biopython library would be the "safest approach". 

However, I don't see why users couldn't just parse the tuple provided by fastq-and-furious, e.g. 

```
from fastqandfurious import fastqandfurious
from fastqandfurious.fastqandfurious import entryfunc

## open for writing

writeFastq = open('another/fastq/file.fastq', 'w') 

bufsize = 20000
with open("a/fastq/file.fq", "rb") as fh:
    it = fastqandfurious.readfastq_iter(fh, bufsize, entryfunc)
    for sequence in it:
        record = ['@'+sequence[0].decode(), sequence[1].decode(), '+', sequence[2].decode()]
        for row in record:
            writeFastq.write("%s\n" % row)

writeFastq.close()
```

Am I mistaken somewhere? (It's very possible...)

Thanks for the help

**Comment by evanbiederstedt** [comment]
Opened another PR to address this: https://github.com/lgautier/fastq-and-furious/pull/8

That should complete all of the README edits I think

**Comment by lgautier** [comment]
(...)
> However, I don't see why users couldn't just parse the tuple provided by fastq-and-furious, e.g.

They certainly can, if I understand your intent correctly. The function shown in the doc is showing slightly different: how to to produce Biopython `SeqRecord` objects using this parser.

Note that this library differs slightly from other libraries by providing element positions (that is offset and length for header, sequence, quality) from which a user can decide to build objects or process the FASTQ entry as he or she wants. For example, the section "Performance by design" has the following:

```
 the approach opens the door for implementing masking strategies to avoid saving
FASTQ after each filtering or read-trimming step. Excluding reads or trimming either
end of the read could be done by only deleting rows or modifying the values in the table.
```

This means that this parser would allow one to parse a FASTQ file *once* (that is figure out where are the elements of entries) and store the positions (byte offsets) of headers, sequences, etc... into a index. Subsequent parsing of the FASTQ file would then be replaced by simply reading from these positions. The performance benchmark shows that this first parsing is already very efficient with this package, and would just even more efficient if the same FASTQ is to be parsed several times, or would even allow working on indexes when filtering reads, trimming ends, etc... instead of creating copies of subsets of FASTQ files.

**Comment by evanbiederstedt** [comment]
Thanks for the reply @lgautier 

Ah yes, I see your point now:

> The performance benchmark shows that this first parsing is already very efficient with this package, and would just even more efficient if the same FASTQ is to be parsed several times, or would even allow working on indexes when filtering reads, trimming ends, etc... instead of creating copies of subsets of FASTQ files

Right, I think this makes a great deal of sense. Perfect! I understand the motivation for this example a bit more, and this removes some of the lingering confusion I had.

Thank you for the help!

**Comment by evanbiederstedt** [comment]
Hi @lgautier

I was reminded of this conversation recently. 

Does `fastq-and-furious` contain the functionality to write fastqs? Would that be worth a feature request?

I ask as, I noticed some problems with my scheme here:

```
from fastqandfurious import fastqandfurious
from fastqandfurious.fastqandfurious import entryfunc

## open for writing

writeFastq = open('another/fastq/file.fastq', 'w') 

bufsize = 20000
with open("a/fastq/file.fq", "rb") as fh:
    it = fastqandfurious.readfastq_iter(fh, bufsize, entryfunc)
    for sequence in it:
        record = ['@'+sequence[0].decode(), sequence[1].decode(), '+', sequence[2].decode()]
        for row in record:
            writeFastq.write("%s\n" % row)

writeFastq.close()

```

**Comment by evanbiederstedt** [comment]
On second thought, the library works perfectly. I was noticing some odd behavior, but it's outside of the scope of `fastq-and-furious`. 

Please disregard :)
